/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#2f4155",
        "on-secondary-fixed": "#3d4041",
        "on-background": "#e7e5e5",
        "primary-dim": "#9cbcdd",
        "tertiary-container": "#d1e4fe",
        "on-secondary": "#1e2122",
        "on-tertiary-fixed-variant": "#4b5d72",
        "surface-bright": "#2b2c2c",
        "on-tertiary": "#495c71",
        "outline": "#767575",
        "inverse-surface": "#fcf9f8",
        "tertiary-fixed": "#d1e4fe",
        "surface": "#0e0e0e",
        "surface-tint": "#a9caeb",
        "surface-dim": "#0e0e0e",
        "secondary-container": "#393c3d",
        "on-primary-fixed": "#20425e",
        "error": "#ee7d77",
        "on-primary-container": "#b3d4f6",
        "on-primary-fixed-variant": "#3e5e7b",
        "tertiary-fixed-dim": "#c3d6ef",
        "error-container": "#7f2927",
        "on-error": "#490106",
        "tertiary": "#e9f1ff",
        "secondary": "#9c9ea0",
        "surface-container-highest": "#252626",
        "on-surface": "#e7e5e5",
        "surface-variant": "#252626",
        "secondary-fixed": "#e1e2e4",
        "on-tertiary-container": "#415368",
        "on-secondary-fixed-variant": "#595c5e",
        "outline-variant": "#484848",
        "surface-container-lowest": "#000000",
        "primary-fixed-dim": "#b7d8fa",
        "surface-container-low": "#131313",
        "primary-fixed": "#cee5ff",
        "tertiary-dim": "#c3d6ef",
        "on-error-container": "#ff9993",
        "surface-container": "#191a1a",
        "secondary-dim": "#9c9ea0",
        "inverse-on-surface": "#565555",
        "background": "#0e0e0e",
        "on-primary": "#21435f",
        "on-secondary-container": "#bebfc1",
        "on-surface-variant": "#acabaa",
        "primary": "#a9caeb",
        "inverse-primary": "#42627f",
        "secondary-fixed-dim": "#d3d4d6",
        "primary-container": "#294965",
        "surface-container-high": "#1f2020",
        "error-dim": "#bb5551"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
